all:
  children:
    app:
      hosts:
        upvy-app:
          ansible_host: "{{ lookup('env', 'UPVY_EC2_HOST') | default('REPLACE_WITH_EIP', true) }}"
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3
